title: Podlove Subscribe Button
description: Description
theme: millidocs

destination: ../dist
baseurl: podlove-web-player/

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
